import Link from 'next/link';
import { ArrowLeft, ArrowRight, BarChart3, Calendar, Check, CheckCircle2, ChevronRight, CircleHelp, Code2, Copy, Download, Eye, FileText, Filter, GripVertical, Link2, Mail, MessageSquare, MoreHorizontal, Pencil, Plus, Search, ShieldCheck, Trash2, Upload, UserPlus, Users, Video } from 'lucide-react';
import { ConsoleButton, ConsoleCard, ConsoleShell, StatusPill } from './ConsoleShell';

const candidates = [
  ['Sarah Jenkins', 'sarah.jenkins@email.com', 'Senior Frontend Engineer', 'Technical Interview', '92', 'green'],
  ['David Chen', 'david.chen@email.com', 'Product Manager', 'Screening', '—', 'blue'],
  ['Priya Sharma', 'priya.sharma@email.com', 'Backend Engineer', 'Completed', '88', 'green'],
  ['Michael Brown', 'michael.b@email.com', 'Senior Frontend Engineer', 'Invited', '—', 'amber'],
  ['Elena Rodriguez', 'elena.r@email.com', 'UX Researcher', 'Completed', '95', 'green'],
] as const;

const interviews = [
  ['Frontend Architect Technical Screen', 'Engineering', 'Active', '24', 'Sep 3, 2026'],
  ['Product Manager — Tier 1', 'Product', 'Active', '18', 'Sep 1, 2026'],
  ['Senior Backend Engineer', 'Engineering', 'Draft', '—', 'Aug 28, 2026'],
  ['UX Researcher Assessment', 'Design', 'Archived', '31', 'Aug 19, 2026'],
] as const;

function candidateSlug(name: string) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
}

function Initials({ name, color = 'blue' }: { name: string; color?: 'blue' | 'purple' | 'amber' | 'green' }) {
  const colors = { blue: 'bg-[#dce9ff] text-[#31588e]', purple: 'bg-[#eee4ff] text-[#69439c]', amber: 'bg-[#fff0cf] text-[#855d12]', green: 'bg-[#def3e4] text-[#347348]' };
  return <span className={`grid size-10 shrink-0 place-items-center rounded-full text-xs font-bold ${colors[color]}`}>{name.split(' ').map(n => n[0]).join('').slice(0, 2)}</span>;
}

function SectionTitle({ title, action }: { title: string; action?: React.ReactNode }) { return <div className="mb-5 flex items-center justify-between gap-4"><h2 className="font-serif text-xl font-bold">{title}</h2>{action}</div>; }
function Field({ label, value, placeholder }: { label: string; value?: string; placeholder?: string }) { return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span><input defaultValue={value} placeholder={placeholder} className="h-11 w-full rounded-lg border border-[#dfe2e6] bg-white px-3 text-sm outline-none focus:border-black" /></label>; }
function SelectField({ label, value }: { label: string; value: string }) { return <label className="block"><span className="mb-2 block text-sm font-semibold">{label}</span><select defaultValue={value} className="h-11 w-full rounded-lg border border-[#dfe2e6] bg-white px-3 text-sm"><option>{value}</option></select></label>; }

export function DashboardScreen() {
  const stats = [['Completion Rate', '84%', '+5.2%', 'green'], ['Average Score', '76.4', '+3.1%', 'green'], ['Pass Rate', '62%', '-1.8%', 'red'], ['Time to Complete', '43m', '-4m', 'green']] as const;
  return <ConsoleShell title="Enterprise Analytics" subtitle="A clear view of your hiring performance and candidate quality." actions={<><ConsoleButton variant="outline"><Download size={16}/> Export</ConsoleButton><ConsoleButton href="/enterprise/builder/basics"><Plus size={16}/> Create Interview</ConsoleButton></>}>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{stats.map(([label, value, delta, tone]) => <ConsoleCard key={label} className="p-5"><div className="flex items-start justify-between"><span className="text-sm text-[#676c74]">{label}</span><BarChart3 size={17} className="text-[#858a92]"/></div><div className="mt-5 flex items-end justify-between"><strong className="font-serif text-3xl">{value}</strong><span className={`text-xs font-semibold ${tone === 'green' ? 'text-[#258044]' : 'text-[#b0443d]'}`}>{delta}</span></div><p className="mt-1 text-xs text-[#969aa1]">vs previous 30 days</p></ConsoleCard>)}</div>
    <div className="mt-5 grid gap-5 xl:grid-cols-[1.55fr_1fr]">
      <ConsoleCard className="p-6"><SectionTitle title="Hiring Funnel" action={<button className="text-sm text-[#6c7179]">Last 30 days⌄</button>}/><div className="flex h-[260px] items-end gap-5 border-b border-l border-[#e6e8eb] px-5 pb-0">{[['Invited',218,100],['Started',176,81],['Completed',149,68],['Passed',92,42],['Hired',28,13]].map(([l,n,h]) => <div key={l} className="flex flex-1 flex-col items-center"><span className="mb-2 text-sm font-bold">{n}</span><div className="w-full rounded-t-md bg-[#202124]" style={{height:`${h}%`}}/><span className="mt-3 text-xs text-[#686d74]">{l}</span></div>)}</div></ConsoleCard>
      <ConsoleCard className="p-6"><SectionTitle title="Performance by Skill"/><div className="space-y-5">{[['Problem Solving',82],['System Design',74],['Communication',79],['Technical Depth',68],['Product Thinking',76]].map(([skill, score]) => <div key={skill as string}><div className="mb-2 flex justify-between text-sm"><span>{skill}</span><b>{score}</b></div><div className="h-2 rounded-full bg-[#edf0f2]"><div className="h-2 rounded-full bg-[#242526]" style={{width:`${score}%`}}/></div></div>)}</div></ConsoleCard>
    </div>
    <ConsoleCard className="mt-5 overflow-hidden"><div className="p-6"><SectionTitle title="Recent Interviews" action={<Link href="/enterprise/interviews" className="text-sm font-semibold">View all <ArrowRight size={14} className="inline"/></Link>}/></div><InterviewTable compact/></ConsoleCard>
  </ConsoleShell>;
}

function InterviewTable({ compact = false }: { compact?: boolean }) { return <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead className="border-y border-[#e7e9ec] bg-[#fafbfc] text-left text-[11px] uppercase tracking-wider text-[#777c84]"><tr><th className="px-6 py-3">Interview</th><th className="px-6 py-3">Department</th><th className="px-6 py-3">Status</th><th className="px-6 py-3">Candidates</th><th className="px-6 py-3">Last updated</th><th className="px-6 py-3"/></tr></thead><tbody>{interviews.slice(0, compact ? 3 : undefined).map((row) => <tr key={row[0]} className="border-b border-[#eceef0] last:border-0"><td className="px-6 py-4"><Link href="/enterprise/interviews/frontend-architect" className="font-semibold hover:underline">{row[0]}</Link></td><td className="px-6 py-4 text-[#656a72]">{row[1]}</td><td className="px-6 py-4"><StatusPill tone={row[2] === 'Active' ? 'green' : row[2] === 'Draft' ? 'amber' : 'gray'}>{row[2]}</StatusPill></td><td className="px-6 py-4">{row[3]}</td><td className="px-6 py-4 text-[#656a72]">{row[4]}</td><td className="px-6 py-4 text-right"><MoreHorizontal size={18}/></td></tr>)}</tbody></table></div>; }

export function InterviewsScreen() { return <ConsoleShell title="Interviews" subtitle="Create, manage, and track every interview process." actions={<ConsoleButton href="/enterprise/builder/basics"><Plus size={16}/> Create Interview</ConsoleButton>}><div className="mb-5 flex flex-wrap items-center gap-2 border-b border-[#dedfe2]">{['All interviews','Draft','Active','Completed','Archived'].map((x,i)=><button key={x} className={`px-4 pb-3 text-sm font-semibold ${i===0?'border-b-2 border-black text-black':'text-[#747981]'}`}>{x}</button>)}</div><ConsoleCard className="overflow-hidden"><div className="flex flex-wrap gap-3 p-5"><div className="relative min-w-[260px] flex-1"><Search size={16} className="absolute left-3 top-3 text-[#888]"/><input placeholder="Search interviews" className="h-10 w-full rounded-lg border border-[#dfe2e6] pl-9 text-sm"/></div><ConsoleButton variant="outline"><Filter size={16}/> Filters</ConsoleButton><ConsoleButton variant="outline">Sort: Recently updated</ConsoleButton></div><InterviewTable/></ConsoleCard></ConsoleShell>; }

export function TemplatesScreen() { const cards = [['Blank Template','Start from scratch with complete control.','Create blank'],['Senior Frontend Engineer','React, architecture, coding and communication.','Use template'],['Product Manager — Tier 1','Product sense, execution and analytics.','Use template'],['System Design Expert','Scalability, reliability and trade-off analysis.','Use template']]; return <ConsoleShell title="Interview Templates" subtitle="Launch faster with role-ready interview structures created by hiring experts." actions={<ConsoleButton href="/enterprise/interviews">View interviews</ConsoleButton>}><div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{cards.map((c,i)=><ConsoleCard key={c[0]} className={`flex min-h-[300px] flex-col p-6 ${i===0?'border-dashed bg-[#fbfbfc]':''}`}><span className={`grid size-11 place-items-center rounded-lg ${i===0?'border border-[#d8dce1]':'bg-[#eef2f7]'}`}>{i===0?<Plus size={20}/>:<FileText size={20}/>}</span><h2 className="mt-7 font-serif text-xl font-bold">{c[0]}</h2><p className="mt-3 text-sm leading-6 text-[#666b73]">{c[1]}</p>{i>0&&<div className="mt-5 flex flex-wrap gap-2 text-xs text-[#666b73]"><span className="rounded bg-[#f1f3f5] px-2 py-1">60 mins</span><span className="rounded bg-[#f1f3f5] px-2 py-1">4 stages</span></div>}<ConsoleButton href="/enterprise/builder/basics" variant={i===0?'outline':'solid'}>{c[2]} <ArrowRight size={15}/></ConsoleButton></ConsoleCard>)}</div></ConsoleShell>; }

export function CandidatesScreen() { return <ConsoleShell title="Candidate Pipeline" subtitle="Track candidate progress and move your best applicants forward." actions={<><ConsoleButton href="/enterprise/candidates/empty" variant="outline">Empty state</ConsoleButton><ConsoleButton variant="outline"><Upload size={16}/> Import CSV</ConsoleButton><ConsoleButton href="/enterprise/invitations"><UserPlus size={16}/> Invite Candidates</ConsoleButton></>}><div className="mb-5 grid gap-4 sm:grid-cols-3">{[['All candidates','148'],['In progress','37'],['Completed','94']].map(([l,n])=><ConsoleCard key={l} className="p-5"><p className="text-sm text-[#6d727a]">{l}</p><strong className="mt-1 block font-serif text-3xl">{n}</strong></ConsoleCard>)}</div><ConsoleCard className="overflow-hidden"><div className="flex flex-wrap gap-3 p-5"><div className="relative min-w-[260px] flex-1"><Search size={16} className="absolute left-3 top-3 text-[#888]"/><input placeholder="Search by name or email" className="h-10 w-full rounded-lg border border-[#dfe2e6] pl-9 text-sm"/></div><ConsoleButton variant="outline"><Filter size={16}/> Role</ConsoleButton><ConsoleButton variant="outline">Status</ConsoleButton></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="border-y border-[#e7e9ec] bg-[#fafbfc] text-left text-[11px] uppercase tracking-wider text-[#777c84]"><tr><th className="px-6 py-3">Candidate</th><th className="px-6 py-3">Role applied</th><th className="px-6 py-3">Status</th><th className="px-6 py-3">AI score</th><th className="px-6 py-3">Action</th></tr></thead><tbody>{candidates.map((c,i)=><tr key={c[0]} className="border-b border-[#eceef0]"><td className="px-6 py-4"><div className="flex items-center gap-3"><Initials name={c[0]} color={i%2?'purple':'blue'}/><div><Link href={`/enterprise/candidates/${candidateSlug(c[0])}/report`} className="font-semibold hover:underline">{c[0]}</Link><p className="text-xs text-[#858a92]">{c[1]}</p></div></div></td><td className="px-6 py-4">{c[2]}</td><td className="px-6 py-4"><StatusPill tone={c[5]}>{c[3]}</StatusPill></td><td className="px-6 py-4 font-bold">{c[4]}</td><td className="px-6 py-4"><Link className="font-semibold underline-offset-4 hover:underline" href={`/enterprise/candidates/${candidateSlug(c[0])}/report`}>View report</Link></td></tr>)}</tbody></table></div></ConsoleCard></ConsoleShell>; }

export function CandidateProfileScreen() { return <ConsoleShell eyebrow="Candidates / Sarah Jenkins" title="Candidate Profile" actions={<><ConsoleButton variant="outline"><Mail size={16}/> Email</ConsoleButton><ConsoleButton>Advance Candidate</ConsoleButton></>}><div className="grid gap-5 xl:grid-cols-[330px_1fr]"><div className="space-y-5"><ConsoleCard className="p-6 text-center"><Initials name="Sarah Jenkins" color="purple"/><h2 className="mt-4 font-serif text-2xl font-bold">Sarah Jenkins</h2><p className="mt-1 text-sm text-[#6e737b]">Senior Frontend Engineer</p><StatusPill tone="blue">Technical Interview</StatusPill><div className="mt-6 border-t border-[#e8eaed] pt-5 text-left text-sm"><p className="mb-3"><b>Email</b><br/><span className="text-[#6d7279]">sarah.jenkins@email.com</span></p><p><b>Location</b><br/><span className="text-[#6d7279]">San Francisco, CA</span></p></div></ConsoleCard><ConsoleCard className="p-6"><SectionTitle title="Key Skills"/><div className="flex flex-wrap gap-2">{['React','TypeScript','System Design','Accessibility','GraphQL'].map(x=><span key={x} className="rounded-md bg-[#f0f2f5] px-2.5 py-1.5 text-xs font-semibold">{x}</span>)}</div></ConsoleCard></div><div className="space-y-5"><ConsoleCard className="p-6"><SectionTitle title="Interview Progress"/><div className="grid gap-4 sm:grid-cols-3">{[['Screening','Completed','green'],['Technical Interview','Sep 5, 10:30 AM','blue'],['Hiring Manager','Pending','gray']].map(x=><div key={x[0]} className="rounded-lg border border-[#e4e7ea] p-4"><CheckCircle2 size={20}/><b className="mt-4 block text-sm">{x[0]}</b><span className="mt-1 block text-xs text-[#747981]">{x[1]}</span></div>)}</div></ConsoleCard><ConsoleCard className="p-6"><SectionTitle title="Experience Summary"/><p className="text-sm leading-7 text-[#5f646c]">Senior frontend engineer with 7+ years building scalable web products. Led a design-system migration used by twelve product teams and improved core web performance by 34%.</p></ConsoleCard><ConsoleCard className="p-6"><SectionTitle title="Resume" action={<ConsoleButton variant="outline"><Download size={15}/> Download</ConsoleButton>}/><div className="flex items-center gap-3 rounded-lg border border-[#e3e6e9] p-4"><FileText/><div><b className="text-sm">Sarah_Jenkins_Resume.pdf</b><p className="text-xs text-[#777c84]">PDF · 1.8 MB</p></div></div></ConsoleCard></div></div></ConsoleShell>; }

// InvitationsScreen used to live here as a fixture: four hardcoded names and
// buttons that did nothing. It is now components/console/EnterpriseInvitations.tsx,
// backed by the interview_invitations table.

export function LiveScreen() { return <ConsoleShell title="Live Sessions Console" subtitle="Monitor active interviews and step in when candidates need support." actions={<ConsoleButton variant="outline"><Calendar size={16}/> Schedule</ConsoleButton>}><div className="mb-5 flex items-center gap-2 text-sm"><span className="size-2 rounded-full bg-[#2f9e54]"/><b>2 live now</b><span className="text-[#777c84]">· 4 scheduled today</span></div><div className="grid gap-5 xl:grid-cols-2">{[['Sarah Jenkins','Senior Frontend Engineer','Technical interview','32:18'],['David Chen','Product Manager','Case study discussion','18:04']].map((s,i)=><ConsoleCard key={s[0]} className="overflow-hidden"><div className="relative grid h-48 place-items-center bg-[#202329] text-white"><Video size={42} strokeWidth={1}/><span className="absolute left-4 top-4 flex items-center gap-2 rounded-full bg-[#c53a32] px-3 py-1 text-xs font-bold"><span className="size-1.5 rounded-full bg-white"/>LIVE</span><span className="absolute bottom-4 right-4 rounded bg-black/60 px-2 py-1 text-xs">{s[3]}</span></div><div className="p-5"><div className="flex items-center gap-3"><Initials name={s[0]} color={i?'purple':'blue'}/><div><h2 className="font-serif text-lg font-bold">{s[0]}</h2><p className="text-xs text-[#777c84]">{s[1]} · {s[2]}</p></div></div><div className="mt-5 flex gap-3"><ConsoleButton variant="outline"><Eye size={15}/> Observe</ConsoleButton><ConsoleButton><MessageSquare size={15}/> Join session</ConsoleButton></div></div></ConsoleCard>)}</div></ConsoleShell>; }

function SimpleTable({ heads, rows }: { heads: string[]; rows: readonly (readonly string[])[] }) { return <div className="overflow-x-auto"><table className="w-full min-w-[680px] text-sm"><thead className="border-y border-[#e7e9ec] bg-[#fafbfc] text-left text-[11px] uppercase tracking-wider text-[#777c84]"><tr>{heads.map(h=><th key={h} className="px-6 py-3">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={`${r[0]}-${i}`} className="border-b border-[#eceef0] last:border-0">{r.map((c,j)=><td key={`${j}-${c}`} className={`px-6 py-4 ${j===0?'font-semibold':'text-[#626770]'}`}>{c}</td>)}</tr>)}</tbody></table></div>; }

export function ComparisonScreen() { const people=[['Elena R.','94','Strong Hire'],['Marcus C.','86','Hire'],['Sarah J.','82','Hire']]; return <ConsoleShell title="Candidate Comparison" subtitle="Compare finalists across the same evaluation criteria." actions={<ConsoleButton variant="outline"><Download size={16}/> Export comparison</ConsoleButton>}><div className="grid gap-4 lg:grid-cols-3">{people.map((p,i)=><ConsoleCard key={p[0]} className={`p-6 ${i===0?'ring-2 ring-black':''}`}><div className="flex items-center gap-3"><Initials name={p[0]} color={i===0?'blue':i===1?'purple':'amber'}/><div><h2 className="font-serif text-xl font-bold">{p[0]}</h2><p className="text-xs text-[#747981]">Senior Frontend Engineer</p></div></div><div className="my-6 flex items-end justify-between"><strong className="font-serif text-4xl">{p[1]}</strong><StatusPill tone="green">{p[2]}</StatusPill></div>{[['Technical',i===0?96:88],['System Design',i===0?91:84],['Communication',i===2?94:89]].map(x=><div key={x[0]} className="mb-4"><div className="mb-1 flex justify-between text-xs"><span>{x[0]}</span><b>{x[1]}</b></div><div className="h-1.5 rounded bg-[#eceef0]"><div className="h-full rounded bg-black" style={{width:`${x[1]}%`}}/></div></div>)}<ConsoleButton href="/enterprise/candidates/sarah-jenkins" variant="outline">View profile</ConsoleButton></ConsoleCard>)}</div></ConsoleShell>; }

export function InterviewDetailScreen() { return <ConsoleShell eyebrow="Interviews / Active" title="Frontend Architect Technical Screen" subtitle="Engineering · Created by Alex Rivera" actions={<><ConsoleButton variant="outline"><Pencil size={15}/> Edit</ConsoleButton><ConsoleButton><UserPlus size={15}/> Invite Candidate</ConsoleButton></>}><div className="mb-7 flex gap-6 border-b border-[#dfe2e6]">{['Overview','Candidates','Sessions','Configuration'].map((x,i)=><button key={x} className={`pb-3 text-sm font-semibold ${i===0?'border-b-2 border-black':'text-[#747981]'}`}>{x}</button>)}</div><div className="grid gap-5 xl:grid-cols-[1fr_330px]"><div className="space-y-5"><ConsoleCard className="p-6"><SectionTitle title="Candidate Pipeline" action={<Link href="/enterprise/candidates" className="text-sm font-semibold">View all</Link>}/><div className="grid gap-4 sm:grid-cols-4">{[['Invited','24'],['In progress','8'],['Completed','12'],['Qualified','7']].map(x=><div key={x[0]} className="rounded-lg bg-[#f5f6f8] p-4"><strong className="font-serif text-2xl">{x[1]}</strong><p className="mt-1 text-xs text-[#72777f]">{x[0]}</p></div>)}</div></ConsoleCard><ConsoleCard className="p-6"><SectionTitle title="Scheduled Sessions"/>{[['Sarah Jenkins','Today · 10:30 AM'],['Michael Brown','Tomorrow · 2:00 PM']].map(x=><div key={x[0]} className="flex items-center gap-3 border-t border-[#e7e9ec] py-4"><Initials name={x[0]}/><div><b className="text-sm">{x[0]}</b><p className="text-xs text-[#737880]">{x[1]}</p></div><ConsoleButton variant="outline">View session</ConsoleButton></div>)}</ConsoleCard></div><div className="space-y-5"><ConsoleCard className="p-6"><SectionTitle title="Configuration"/><dl className="space-y-4 text-sm">{[['Duration','60 min'],['Stages','5'],['Questions','12'],['AI interviewer','Marcus']].map(x=><div key={x[0]} className="flex justify-between"><dt className="text-[#777c84]">{x[0]}</dt><dd className="font-semibold">{x[1]}</dd></div>)}</dl></ConsoleCard><ConsoleCard className="p-6"><SectionTitle title="Collaborators"/><div className="flex -space-x-2">{['Alex Rivera','Maya Patel','Jon Bell'].map((x,i)=><Initials key={x} name={x} color={i===1?'purple':'blue'}/>)}</div></ConsoleCard></div></div></ConsoleShell>; }

const builderSteps = [
  ['basics','Basics'],['structure','Structure'],['questions','Questions'],['ai','AI Configuration'],['rubric','Rubric'],['candidate-settings','Candidate Settings'],['review','Review & Publish'],
] as const;

function BuilderFrame({ step, children, title, subtitle }: { step: string; children: React.ReactNode; title: string; subtitle: string }) { const index=builderSteps.findIndex(x=>x[0]===step); const prev=index>0?builderSteps[index-1][0]:'/enterprise/interviews'; const next=index<builderSteps.length-1?builderSteps[index+1][0]:'published'; return <ConsoleShell flush><div className="border-b border-[#e3e5e8] bg-white px-5 py-5 lg:px-9"><div className="mx-auto flex max-w-[1180px] items-center justify-between"><div><p className="text-xs font-semibold uppercase tracking-wider text-[#777c84]">Interview Builder</p><b className="font-serif text-xl">Frontend Architect</b></div><span className="text-sm text-[#676c74]">Draft saved</span></div><div className="mx-auto mt-5 flex max-w-[1180px] overflow-x-auto">{builderSteps.map(([slug,label],i)=><Link href={`/enterprise/builder/${slug}`} key={slug} className={`min-w-max flex-1 border-b-2 px-3 pb-3 text-center text-xs font-semibold ${i<=index?'border-black text-black':'border-[#dfe2e6] text-[#8a8f96]'}`}><span className={`mr-2 inline-grid size-5 place-items-center rounded-full ${i<index?'bg-black text-white':i===index?'border border-black':'border border-[#ccd0d5]'}`}>{i<index?<Check size={12}/>:i+1}</span>{label}</Link>)}</div></div><div className="mx-auto max-w-[980px] px-5 py-9"><h1 className="font-serif text-3xl font-bold">{title}</h1><p className="mt-2 text-sm text-[#686d75]">{subtitle}</p><div className="mt-7">{children}</div><div className="mt-8 flex justify-between border-t border-[#e1e4e7] pt-6"><ConsoleButton variant="outline" href={typeof prev==='string'&&prev.startsWith('/')?prev:`/enterprise/builder/${prev}`}><ArrowLeft size={15}/> Back</ConsoleButton><ConsoleButton href={`/enterprise/builder/${next}`}>Save & Continue <ArrowRight size={15}/></ConsoleButton></div></div></ConsoleShell>; }

export function BuilderScreen({ step }: { step: string }) {
  if(step==='basics') return <BuilderFrame step={step} title="Basic Information" subtitle="Define the role and the purpose of this interview."><ConsoleCard className="grid gap-6 p-7 md:grid-cols-2"><div className="md:col-span-2"><Field label="Interview title" value="Frontend Architect Technical Screen"/></div><Field label="Target role" value="Frontend Architect"/><SelectField label="Department" value="Engineering"/><SelectField label="Seniority level" value="Senior / Staff"/><SelectField label="Estimated duration" value="60 minutes"/><label className="md:col-span-2"><span className="mb-2 block text-sm font-semibold">Interview description</span><textarea defaultValue="Evaluate architecture, React expertise, problem solving, and technical communication." className="min-h-28 w-full rounded-lg border border-[#dfe2e6] p-3 text-sm"/></label><div className="md:col-span-2"><span className="mb-2 block text-sm font-semibold">Core skills</span><div className="flex flex-wrap gap-2">{['React','TypeScript','System Design','Web Performance'].map(x=><span key={x} className="rounded-md bg-[#eff1f3] px-3 py-2 text-sm">{x} ×</span>)}<button className="rounded-md border border-dashed border-[#babfc6] px-3 py-2 text-sm">+ Add skill</button></div></div></ConsoleCard></BuilderFrame>;
  if(step==='structure') return <BuilderFrame step={step} title="Structure & Stages" subtitle="Arrange the interview stages and tune their duration."><div className="grid gap-5 lg:grid-cols-[1fr_280px]"><div className="space-y-3">{[['Introduction & Warm-up','5 min'],['Technical Screen','20 min'],['Live Coding Challenge','25 min'],['Candidate Questions','10 min']].map((x,i)=><ConsoleCard key={x[0]} className="flex items-center gap-4 p-5"><GripVertical className="text-[#a1a5ac]"/><span className="grid size-9 place-items-center rounded-lg bg-[#f0f2f4] font-bold">{i+1}</span><div className="flex-1"><b>{x[0]}</b><p className="text-xs text-[#797e86]">{x[1]}</p></div><Pencil size={16}/><Trash2 size={16} className="text-[#8b8f96]"/></ConsoleCard>)}<button className="flex w-full items-center justify-center gap-2 rounded-xl border border-dashed border-[#bfc4ca] p-5 text-sm font-semibold"><Plus size={16}/> Add stage</button></div><ConsoleCard className="h-fit p-6"><SectionTitle title="Pipeline Summary"/><p className="text-sm text-[#737880]">4 stages</p><strong className="mt-1 block font-serif text-3xl">60 min</strong><p className="mt-5 text-xs leading-5 text-[#7d8289]">Candidates move through each stage in sequence. You can add up to eight stages.</p></ConsoleCard></div></BuilderFrame>;
  if(step==='questions') return <BuilderFrame step={step} title="Question Library" subtitle="Choose questions for each stage or let RecruitPro select from your library."><div className="grid gap-5 lg:grid-cols-[1fr_300px]"><ConsoleCard className="p-6"><div className="mb-5 flex gap-3"><div className="relative flex-1"><Search size={15} className="absolute left-3 top-3"/><input className="h-10 w-full rounded-lg border border-[#dfe2e6] pl-9 text-sm" placeholder="Search questions"/></div><ConsoleButton variant="outline"><Filter size={15}/> Filter</ConsoleButton></div>{[["Explain the nuances of React's Virtual DOM and reconciliation process.",'Technical depth · Medium'],['Design a large-scale frontend application state management strategy.','System design · Hard'],['Implement an LRU cache with a fixed capacity.','Coding · Medium'],['Tell me about a difficult technical trade-off you made.','Behavioral · Medium']].map((x)=><div key={x[0]} className="border-t border-[#e5e7ea] py-5"><div className="flex gap-3"><span className="grid size-8 shrink-0 place-items-center rounded bg-[#f0f2f4]"><Code2 size={15}/></span><div className="flex-1"><b className="text-sm">{x[0]}</b><p className="mt-1 text-xs text-[#777c84]">{x[1]}</p></div><button className="grid size-8 place-items-center rounded border border-[#d9dde1]"><Plus size={15}/></button></div></div>)}</ConsoleCard><ConsoleCard className="h-fit p-6"><SectionTitle title="Interview Script"/><p className="text-xs text-[#737880]">Technical Screen</p><div className="my-4 rounded-lg border border-[#e1e4e7] p-3 text-sm"><b>3 questions</b><p className="mt-1 text-xs text-[#777c84]">Estimated 20 minutes</p></div><button className="text-sm font-semibold">Auto-select questions</button></ConsoleCard></div></BuilderFrame>;
  if(step==='ai') return <BuilderFrame step={step} title="AI Interviewer Configuration" subtitle="Choose the interviewer voice, persona, and conversation behavior."><div className="grid gap-5 lg:grid-cols-[1fr_330px]"><div className="space-y-5"><ConsoleCard className="p-6"><SectionTitle title="Voice & Persona"/><div className="grid gap-3 sm:grid-cols-3">{[['Marcus','US English'],['Sarah','UK English'],['David','US English']].map((x,i)=><button key={x[0]} className={`rounded-lg border p-4 text-left ${i===0?'border-black ring-1 ring-black':'border-[#dfe2e6]'}`}><Initials name={x[0]}/><b className="mt-3 block text-sm">{x[0]}</b><span className="text-xs text-[#777c84]">{x[1]}</span></button>)}</div></ConsoleCard><ConsoleCard className="p-6"><SectionTitle title="Conversation Style"/>{[['Warmth',65],['Challenge level',72],['Verbosity',38]].map(x=><label key={x[0]} className="mb-5 block text-sm"><span className="mb-2 flex justify-between"><b>{x[0]}</b><span>{x[1]}%</span></span><input type="range" defaultValue={x[1]} className="w-full accent-black"/></label>)}</ConsoleCard><ConsoleCard className="p-6"><SectionTitle title="Interruption Policy"/><div className="space-y-3">{['Wait until candidate finishes speaking','Allow natural conversational interruptions','Only interrupt after extended silence'].map((x,i)=><label key={x} className="flex gap-3 rounded-lg border border-[#e2e5e8] p-4 text-sm"><input type="radio" name="interrupt" defaultChecked={i===0}/>{x}</label>)}</div></ConsoleCard></div><ConsoleCard className="h-fit overflow-hidden"><div className="grid h-40 place-items-center bg-[#24272c] text-white"><span className="grid size-20 place-items-center rounded-full bg-white/10 text-2xl font-serif">M</span></div><div className="p-6"><h2 className="font-serif text-xl font-bold">Marcus</h2><p className="mt-2 text-sm leading-6 text-[#676c74]">Calm, precise, and encouraging. Gives candidates room to think before following up.</p><ConsoleButton variant="outline"><Video size={15}/> Preview voice</ConsoleButton></div></ConsoleCard></div></BuilderFrame>;
  if(step==='rubric') return <BuilderFrame step={step} title="Question & Evaluation-Rubric Editor" subtitle="Define what excellent, acceptable, and weak answers look like."><div className="grid gap-5 lg:grid-cols-[310px_1fr]"><ConsoleCard className="h-fit p-5"><SectionTitle title="Stage Questions"/>{['React reconciliation','Frontend state architecture','LRU cache implementation','Technical trade-off'].map((x,i)=><button key={x} className={`mb-2 w-full rounded-lg p-3 text-left text-sm ${i===0?'bg-[#eff1f3] font-semibold':'hover:bg-[#f7f8fa]'}`}><span className="mr-2 text-[#858a92]">{i+1}.</span>{x}</button>)}</ConsoleCard><ConsoleCard className="p-6"><SectionTitle title="Edit Rubric"/><p className="mb-5 text-sm font-semibold">Explain the nuances of React&apos;s Virtual DOM and reconciliation process.</p>{[['Excellent — 4','Explains fiber, diffing heuristics, keys, batching, and performance trade-offs.'],['Good — 3','Correctly explains virtual DOM, reconciliation, and the importance of stable keys.'],['Developing — 2','Understands the high-level concept but misses implementation details.'],['Insufficient — 1','Provides an incorrect or materially incomplete explanation.']].map(x=><div key={x[0]} className="mb-4 rounded-lg border border-[#e0e3e7] p-4"><b className="text-sm">{x[0]}</b><textarea defaultValue={x[1]} className="mt-2 min-h-16 w-full resize-none rounded border border-[#e2e5e8] p-2 text-sm text-[#626770]"/></div>)}<Field label="Evaluator notes" placeholder="Optional guidance for the AI evaluator"/></ConsoleCard></div></BuilderFrame>;
  if(step==='candidate-settings') return <BuilderFrame step={step} title="Candidate Settings" subtitle="Configure access, identity verification, and the candidate experience."><div className="space-y-5"><ConsoleCard className="grid gap-5 p-6 md:grid-cols-2"><div className="md:col-span-2"><SectionTitle title="Access & Deadlines"/></div><SelectField label="Invitation expires after" value="7 days"/><SelectField label="Retake policy" value="One attempt"/><Field label="Earliest start date" value="September 4, 2026"/><Field label="Completion deadline" value="September 11, 2026"/></ConsoleCard><ConsoleCard className="p-6"><SectionTitle title="Verification"/><div className="space-y-4">{[['Require camera','Candidate camera must remain enabled.'],['Photo identity check','Capture a photo before the interview begins.'],['Browser integrity monitoring','Detect tab switching and window changes.']].map((x,i)=><label key={x[0]} className="flex justify-between gap-4 border-t border-[#e5e7ea] py-4 first:border-0"><span><b className="text-sm">{x[0]}</b><p className="mt-1 text-xs text-[#777c84]">{x[1]}</p></span><input type="checkbox" defaultChecked={i<2} className="size-4 accent-black"/></label>)}</div></ConsoleCard><ConsoleCard className="p-6"><SectionTitle title="Candidate Instructions"/><textarea defaultValue="Find a quiet space, test your microphone and camera, and set aside 60 uninterrupted minutes." className="min-h-28 w-full rounded-lg border border-[#dfe2e6] p-3 text-sm"/></ConsoleCard></div></BuilderFrame>;
  return <BuilderFrame step="review" title="Review & Publish" subtitle="Review the complete candidate experience before making it live."><div className="space-y-4">{[['Basic Information','Frontend Architect Technical Screen · Engineering · 60 minutes'],['Structure & Stages','4 stages · Introduction, Technical Screen, Live Coding, Candidate Questions'],['Question Library','12 questions · 4 required · 8 adaptive'],['AI Configuration','Marcus · Balanced challenge · Patient interruption policy'],['Evaluation Rubric','4 scored competencies · 100 point scale'],['Candidate Settings','7 day expiry · Camera required · One attempt']].map((x,i)=><ConsoleCard key={x[0]} className="flex items-center gap-4 p-5"><span className="grid size-9 place-items-center rounded-full bg-[#e9f5ed] text-[#2f7d47]"><Check size={17}/></span><div className="flex-1"><b>{x[0]}</b><p className="mt-1 text-xs text-[#737880]">{x[1]}</p></div><Link href={`/enterprise/builder/${builderSteps[i][0]}`}><Pencil size={16}/></Link></ConsoleCard>)}<ConsoleCard className="border-black bg-[#f2f3f4] p-6"><div className="flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-serif text-xl font-bold">Ready to publish?</h2><p className="mt-1 text-sm text-[#676c74]">Publishing creates an invitation link and enables candidate access.</p></div><ConsoleButton href="/enterprise/builder/published">Publish Interview <ArrowRight size={15}/></ConsoleButton></div></ConsoleCard></div></BuilderFrame>;
}

export function PublishedScreen() { return <ConsoleShell flush><div className="grid min-h-[calc(100vh-74px)] place-items-center px-5"><div className="w-full max-w-[680px] text-center"><span className="mx-auto grid size-20 place-items-center rounded-full bg-[#e7f5eb] text-[#2b7c44]"><CheckCircle2 size={40}/></span><h1 className="mt-6 font-serif text-4xl font-bold">Interview Published</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-[#686d75]">Frontend Architect Technical Screen is live and ready for candidates.</p><ConsoleCard className="mt-7 p-6 text-left"><p className="text-xs font-semibold uppercase tracking-wider text-[#777c84]">Candidate invitation link</p><div className="mt-3 flex gap-2"><input readOnly value="recruitpro.com/i/frontend-architect-72kx" className="h-11 flex-1 rounded-lg border border-[#dfe2e6] px-3 text-sm"/><ConsoleButton><Copy size={15}/> Copy</ConsoleButton></div></ConsoleCard><div className="mt-5 grid gap-3 sm:grid-cols-3"><ConsoleButton variant="outline"><Mail size={15}/> Invite via Email</ConsoleButton><ConsoleButton variant="outline"><Upload size={15}/> Bulk Upload</ConsoleButton><ConsoleButton variant="outline"><Users size={15}/> Notify Team</ConsoleButton></div><Link href="/enterprise/interviews/frontend-architect" className="mt-7 inline-flex items-center gap-2 text-sm font-semibold">View interview dashboard <ArrowRight size={15}/></Link></div></div></ConsoleShell>; }

export function TeamScreen() { return <ConsoleShell title="Team Management" subtitle="Manage teammates, roles, and access across your organization." actions={<ConsoleButton><UserPlus size={16}/> Invite Member</ConsoleButton>}><div className="mb-5 grid gap-4 sm:grid-cols-3">{[['Team members','24'],['Active seats','21'],['Pending invites','3']].map(x=><ConsoleCard key={x[0]} className="p-5"><p className="text-sm text-[#747981]">{x[0]}</p><strong className="mt-2 block font-serif text-3xl">{x[1]}</strong></ConsoleCard>)}</div><ConsoleCard className="overflow-hidden"><div className="flex gap-3 p-5"><div className="relative flex-1"><Search size={15} className="absolute left-3 top-3"/><input placeholder="Search team members" className="h-10 w-full rounded-lg border border-[#dfe2e6] pl-9 text-sm"/></div><ConsoleButton href="/enterprise/settings/roles" variant="outline"><ShieldCheck size={16}/> Roles & Permissions</ConsoleButton></div><SimpleTable heads={['Member','Role','Department','Status']} rows={[["Alex Rivera",'Organization Admin','Talent','Active'],['Maya Patel','Hiring Manager','Engineering','Active'],['Jon Bell','Recruiter','Talent','Active'],['Nora Lee','Interviewer','Product','Invited']]}/></ConsoleCard></ConsoleShell>; }

const settingsNav=[['Organization','/enterprise/settings'],['Roles & Permissions','/enterprise/settings/roles'],['Integrations','/enterprise/settings/integrations'],['Billing & Subscription','/enterprise/settings/billing'],['Audit Log','/enterprise/audit-log']];
function SettingsFrame({ active, title, subtitle, children }: { active:string; title:string; subtitle:string; children:React.ReactNode }) { return <ConsoleShell eyebrow="Settings" title={title} subtitle={subtitle}><div className="grid gap-6 lg:grid-cols-[220px_1fr]"><nav className="h-fit space-y-1 rounded-xl border border-[#e2e5e8] bg-white p-2">{settingsNav.map(x=><Link key={x[0]} href={x[1]} className={`block rounded-lg px-3 py-2.5 text-sm ${x[0]===active?'bg-[#eff1f3] font-semibold':'text-[#676c74]'}`}>{x[0]}</Link>)}</nav><div className="space-y-5">{children}</div></div></ConsoleShell>; }
export function SettingsScreen() { return <SettingsFrame active="Organization" title="Settings" subtitle="Manage your organization profile and interview defaults."><ConsoleCard className="grid gap-5 p-6 md:grid-cols-2"><div className="md:col-span-2"><SectionTitle title="Organization Profile"/></div><Field label="Organization name" value="Northstar Labs"/><Field label="Company website" value="https://northstarlabs.com"/><SelectField label="Industry" value="Software & Technology"/><SelectField label="Company size" value="201–500 employees"/><div className="md:col-span-2"><ConsoleButton>Save changes</ConsoleButton></div></ConsoleCard><ConsoleCard className="p-6"><SectionTitle title="Interview Defaults"/><div className="grid gap-5 md:grid-cols-2"><SelectField label="Default time zone" value="Asia/Kolkata (IST)"/><SelectField label="Default interview expiry" value="7 days"/></div></ConsoleCard><ConsoleCard className="p-6"><SectionTitle title="Data Retention"/><p className="text-sm text-[#6b7078]">Candidate interview data is retained for 365 days.</p></ConsoleCard></SettingsFrame>; }
export function RolesScreen() { return <SettingsFrame active="Roles & Permissions" title="Roles & Permissions" subtitle="Control what team members can see and change."><ConsoleCard className="overflow-hidden"><div className="p-6"><SectionTitle title="Permission Matrix" action={<ConsoleButton><Plus size={15}/> Create Role</ConsoleButton>}/></div><SimpleTable heads={['Permission','Admin','Hiring Manager','Recruiter','Interviewer']} rows={[['Manage interviews','✓','✓','✓','—'],['View candidates','✓','✓','✓','✓'],['Manage team','✓','—','—','—'],['View billing','✓','—','—','—'],['Export reports','✓','✓','✓','—']]}/></ConsoleCard><ConsoleCard className="p-6"><SectionTitle title="Active Roles"/><div className="grid gap-3 sm:grid-cols-2">{[['Organization Admin','3 members'],['Hiring Manager','6 members'],['Recruiter','8 members'],['Interviewer','7 members']].map(x=><div key={x[0]} className="rounded-lg border border-[#e2e5e8] p-4"><b className="text-sm">{x[0]}</b><p className="mt-1 text-xs text-[#777c84]">{x[1]}</p></div>)}</div></ConsoleCard></SettingsFrame>; }
export function IntegrationsScreen() { const apps=[['Workday ATS','Sync jobs and candidate stages.','Connected'],['Google Workspace','Calendar and email scheduling.','Connected'],['Microsoft Teams','Interview notifications and calls.','Connect'],['Slack','Hiring team alerts.','Connect']]; return <SettingsFrame active="Integrations" title="Connected Services" subtitle="Connect RecruitPro to the tools your hiring team already uses."><div className="grid gap-4 md:grid-cols-2">{apps.map((a,i)=><ConsoleCard key={a[0]} className="p-6"><span className="grid size-11 place-items-center rounded-lg bg-[#f0f2f4]"><Link2 size={20}/></span><h2 className="mt-5 font-serif text-xl font-bold">{a[0]}</h2><p className="mt-2 min-h-10 text-sm text-[#6b7078]">{a[1]}</p><ConsoleButton variant={i<2?'outline':'solid'}>{a[2]}</ConsoleButton></ConsoleCard>)}</div><ConsoleCard className="p-6"><SectionTitle title="Developer Settings"/><div className="grid gap-4 md:grid-cols-2"><div className="rounded-lg border border-[#e1e4e7] p-4"><b>API Keys</b><p className="mt-1 text-xs text-[#777c84]">Create credentials for internal integrations.</p></div><div className="rounded-lg border border-[#e1e4e7] p-4"><b>Webhooks</b><p className="mt-1 text-xs text-[#777c84]">Subscribe to interview and candidate events.</p></div></div></ConsoleCard></SettingsFrame>; }
export function BillingScreen() { return <SettingsFrame active="Billing & Subscription" title="Billing & Subscription" subtitle="Manage your plan, seats, and payment information."><ConsoleCard className="p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-wider text-[#777c84]">Current plan</p><h2 className="mt-2 font-serif text-3xl font-bold">Enterprise Plus</h2><p className="mt-2 text-sm text-[#676c74]">Renews October 1, 2026 · billed annually</p></div><ConsoleButton variant="outline">Manage plan</ConsoleButton></div></ConsoleCard><div className="grid gap-4 sm:grid-cols-2"><ConsoleCard className="p-6"><p className="text-sm text-[#6d727a]">Seats Usage</p><strong className="mt-2 block font-serif text-3xl">21 / 30</strong><div className="mt-4 h-2 rounded bg-[#eceef0]"><div className="h-2 w-[70%] rounded bg-black"/></div></ConsoleCard><ConsoleCard className="p-6"><p className="text-sm text-[#6d727a]">Interviews This Month</p><strong className="mt-2 block font-serif text-3xl">184</strong><p className="mt-4 text-xs text-[#777c84]">Unlimited on your plan</p></ConsoleCard></div><ConsoleCard className="p-6"><SectionTitle title="Payment Method" action={<button className="text-sm font-semibold">Edit</button>}/><p className="text-sm">Visa ending in 4242 · Expires 08/29</p></ConsoleCard><ConsoleCard className="overflow-hidden"><div className="p-6"><SectionTitle title="Billing History"/></div><SimpleTable heads={['Invoice','Date','Amount','Status']} rows={[['INV-2026-09','Sep 1, 2026','$2,400.00','Paid'],['INV-2026-08','Aug 1, 2026','$2,400.00','Paid'],['INV-2026-07','Jul 1, 2026','$2,400.00','Paid']]}/></ConsoleCard></SettingsFrame>; }
export function AuditScreen() { return <SettingsFrame active="Audit Log" title="Audit Log" subtitle="Review account, permission, and interview configuration activity."><ConsoleCard className="overflow-hidden"><div className="flex gap-3 p-5"><div className="relative flex-1"><Search size={15} className="absolute left-3 top-3"/><input placeholder="Search activity" className="h-10 w-full rounded-lg border border-[#dfe2e6] pl-9 text-sm"/></div><ConsoleButton variant="outline"><Filter size={15}/> Filter</ConsoleButton></div><SimpleTable heads={['Actor','Action','Resource','Time']} rows={[['Alex Rivera','Published interview','Frontend Architect','Today, 9:42 AM'],['Maya Patel','Updated candidate stage','Sarah Jenkins','Today, 8:17 AM'],['Jon Bell','Invited team member','nora@northstar.com','Yesterday'],['Alex Rivera','Changed role permissions','Recruiter','Aug 31, 2026']]}/></ConsoleCard></SettingsFrame>; }

export function NotificationsScreen() { return <ConsoleShell title="Notifications" actions={<button className="text-sm font-semibold">Mark all as read</button>}><div className="mx-auto max-w-[850px]"><div className="mb-5 flex gap-5 border-b border-[#dfe2e6]">{['All','Interviews','Candidates','Team'].map((x,i)=><button key={x} className={`pb-3 text-sm font-semibold ${i===0?'border-b-2 border-black':'text-[#777c84]'}`}>{x}</button>)}</div><ConsoleCard className="divide-y divide-[#e7e9ec]">{[['Candidate completed interview','Sarah Jenkins completed Frontend Architect with a score of 92.','5 minutes ago'],['Live interview starting soon','David Chen is scheduled to start in 15 minutes.','20 minutes ago'],['New team member joined','Nora Lee accepted your invitation.','Yesterday'],['Weekly report is ready','Your Engineering Hiring Summary is ready to download.','Monday']].map((x,i)=><div key={x[0]} className={`flex gap-4 p-5 ${i<2?'bg-[#fafbfd]':''}`}><span className={`mt-1 size-2 shrink-0 rounded-full ${i<2?'bg-[#315ca8]':'bg-transparent'}`}/><div className="flex-1"><b className="text-sm">{x[0]}</b><p className="mt-1 text-sm text-[#666b73]">{x[1]}</p><span className="mt-2 block text-xs text-[#8b9098]">{x[2]}</span></div><MoreHorizontal size={18}/></div>)}</ConsoleCard></div></ConsoleShell>; }

export function SupportScreen() { return <ConsoleShell title="Support Center" subtitle="Find answers, learn RecruitPro, or talk to our team."><ConsoleCard className="bg-[#202225] p-8 text-center text-white"><h2 className="font-serif text-3xl font-bold">How can we help?</h2><div className="relative mx-auto mt-5 max-w-xl"><Search size={18} className="absolute left-4 top-3.5 text-black"/><input placeholder="Search guides and help articles" className="h-12 w-full rounded-lg bg-white pl-11 text-sm text-black"/></div></ConsoleCard><div className="mt-5 grid gap-5 md:grid-cols-3">{[['Getting Started','Set up your organization and first interview.'],['Interview Builder','Create stages, questions, rubrics, and AI behavior.'],['Candidate Management','Invite, track, compare, and report on candidates.']].map(x=><ConsoleCard key={x[0]} className="p-6"><CircleHelp/><h2 className="mt-5 font-serif text-xl font-bold">{x[0]}</h2><p className="mt-2 text-sm leading-6 text-[#676c74]">{x[1]}</p><button className="mt-5 flex items-center gap-1 text-sm font-semibold">Browse articles <ChevronRight size={14}/></button></ConsoleCard>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-[1fr_340px]"><ConsoleCard className="p-6"><SectionTitle title="Open Support Tickets"/><p className="text-sm text-[#676c74]">You have no open tickets.</p></ConsoleCard><ConsoleCard className="p-6"><SectionTitle title="Need Immediate Help?"/><p className="text-sm text-[#676c74]">Enterprise support is available 24/7.</p><ConsoleButton><MessageSquare size={15}/> Start live chat</ConsoleButton></ConsoleCard></div></ConsoleShell>; }

export function OnboardingScreen() { const steps=[['Account Creation','Admin details saved.'],['Organization Profile','Company details and size.'],['Team Members','Invite your recruiters.'],['Billing Setup','Payment information.']]; return <div className="min-h-screen bg-[#f7f8fa] text-[#171819] md:flex"><aside className="hidden w-80 shrink-0 flex-col border-r border-[#dfe2e6] bg-white md:flex"><div className="border-b border-[#e3e5e8] p-10 font-serif text-2xl font-bold">RecruitPro</div><div className="flex-1 p-10"><p className="mb-8 text-xs font-semibold uppercase tracking-wider text-[#697079]">Setup Progress</p><ol className="space-y-8">{steps.map((x,i)=><li key={x[0]} className="flex gap-4"><span className={`relative z-10 grid size-6 shrink-0 place-items-center rounded-full text-xs ${i===0?'bg-black text-white':i===1?'border-2 border-black bg-white':'border-2 border-[#c8ccd1] bg-white'}`}>{i===0?<Check size={13}/>:i===1?<span className="size-2 rounded-full bg-black"/>:''}</span><div><b className={`text-sm ${i>1?'text-[#6f747c]':''}`}>{x[0]}</b><p className="mt-1 text-xs text-[#777c84]">{x[1]}</p></div></li>)}</ol></div><div className="border-t border-[#e3e5e8] bg-[#f7f8fa] p-10 text-xs text-[#696e76]">Need assistance? <Link href="/enterprise/support" className="font-semibold underline">Contact Support</Link></div></aside><main className="flex-1 px-5 py-12 md:px-10 md:py-20"><div className="mx-auto max-w-3xl"><div className="mb-8"><p className="mb-2 text-xs font-semibold text-[#777c84] md:hidden">STEP 2 OF 4</p><h1 className="font-serif text-3xl font-bold">Organization Profile</h1><p className="mt-2 text-sm text-[#666b73]">Tell us about your company to tailor your RecruitPro experience.</p></div><ConsoleCard className="grid gap-6 p-8 md:grid-cols-2"><div className="md:col-span-2"><Field label="Company Name" placeholder="e.g. Acme Corporation"/></div><SelectField label="Industry" value="Select industry"/><SelectField label="Company Size" value="Select size"/><div className="md:col-span-2"><p className="mb-3 text-sm font-semibold">Company Logo (Optional)</p><div className="flex items-center gap-5"><span className="grid size-16 place-items-center rounded-lg border border-dashed border-[#bfc4ca] text-[#7b8088]"><Upload size={20}/></span><ConsoleButton variant="outline">Upload Image</ConsoleButton></div><p className="mt-2 text-xs text-[#777c84]">Recommended size: 400 × 400 px. Max 2 MB.</p></div></ConsoleCard><div className="my-6 flex h-44 items-end rounded-xl bg-gradient-to-br from-[#e8ebee] to-[#cdd4da] p-6"><p className="font-serif text-xl font-bold">Elevate Your Hiring</p></div><div className="flex justify-between border-t border-[#dfe2e6] pt-6"><ConsoleButton variant="outline"><ArrowLeft size={15}/> Back</ConsoleButton><ConsoleButton href="/enterprise">Continue to Team Members <ArrowRight size={15}/></ConsoleButton></div></div></main></div>; }

export function UnknownEnterpriseScreen() { return <ConsoleShell title="Page not found" subtitle="This RecruitPro enterprise page does not exist."><ConsoleButton href="/enterprise">Return to dashboard</ConsoleButton></ConsoleShell>; }
